# -*- mode: python ; coding: utf-8 -*-

from PyInstaller.utils.hooks import collect_dynamic_libs
pil_binaries = collect_dynamic_libs('PIL')

a = Analysis(
    ['app.py'],
    pathex=['..', '.'],
    binaries=[] + pil_binaries,
    datas=[
        ('assets/fonts', 'backend/assets/fonts'),
        ('assets/fonts', 'assets/fonts'),
        ('assets/raqm', 'backend/assets/raqm'),
        ('assets/raqm', 'assets/raqm'),
        ('../python windows sdk/Example/Python_pyd', 'tsc_sdk'),
        ('../python windows sdk/TSCLib.dll', 'tsc_sdk'),
    ],
    hiddenimports=[
        'services',
        'services.barcode_service',
        'services.db_service',
        'services.file_service',
        'services.gmail_service',
        'services.logging_service',
        'services.printer_service',
        'services.printer_capabilities',
        'services.settings_service',
        'services.telemetry_service',
        'services.template_service',
        'drivers',
        'drivers.base_driver',
        'drivers.driver_router',
        'drivers.tspl_driver',
        'drivers.zpl_driver',
        'drivers.epl_driver',
        'drivers.gdi_driver',
        'drivers.pdf_driver',
        'utils',
        'utils.helpers',
        'utils.sdk_loader',
        'raqm_bootstrap',
        'flask',
        'flask_cors',
        'waitress',
        'waitress.server',
        'waitress.task',
        'waitress.channel',
        'waitress.utilities',
        'waitress.buffers',
        'waitress.parser',
        'waitress.receiver',
        'waitress.adjustments',
        'waitress.compat',
        'waitress.trigger',
        'waitress.wasyncore',
        'win32print',
        'win32api',
        'win32con',
        'win32ui',
        'pywintypes',
        'pyodbc',
        'pymysql',
        'barcode',
        'barcode.writer',
        'qrcode',
        'qrcode.image.pil',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'PIL.ImageWin',
        'PIL._imagingft',
        'PIL.features',
        'reportlab',
        'reportlab.pdfgen',
        'reportlab.pdfgen.canvas',
        'reportlab.lib',
        'reportlab.lib.pagesizes',
        'reportlab.lib.units',
        'cryptography',
        'imaplib',
        'email',
        'email.header',
        'email.mime',
        'email.mime.text',
        'email.mime.multipart',
        'sqlite3',
        'json',
        'threading',
        'argparse',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['raqm_bootstrap.py'],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='studio_backend',
    icon='assets/app.ico',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
